#!/usr/bin/env node
/*
 * Build the dotted land data used by the background globe.
 *
 *   node scripts/gen-earth.js <land.geojson> <out.js>
 *
 * Samples a latitude/longitude grid, keeps the points that fall on land, and
 * writes them as a compact array. Rows are spaced evenly in latitude, and the
 * longitude step widens toward the poles so the dots stay roughly equidistant
 * on the sphere instead of bunching up at the top and bottom.
 *
 * Source data: Natural Earth 1:110m land (public domain).
 */
'use strict';

const fs = require('node:fs');

const [, , input, output] = process.argv;
if (!input || !output) {
  console.error('Usage: gen-earth.js <land.geojson> <out.js>');
  process.exit(1);
}

const geo = JSON.parse(fs.readFileSync(input, 'utf8'));

// Flatten to a list of rings, each an array of [lon, lat].
const polygons = [];
for (const feature of geo.features) {
  const g = feature.geometry;
  if (!g) continue;
  const parts = g.type === 'Polygon' ? [g.coordinates]
    : g.type === 'MultiPolygon' ? g.coordinates : [];
  for (const rings of parts) polygons.push(rings);
}

function pointInRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if ((yi > lat) !== (yj > lat) && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

// A polygon is an outer ring plus holes; a point counts as land when it is
// inside the outer ring and outside every hole.
function onLand(lon, lat) {
  for (const rings of polygons) {
    if (!pointInRing(lon, lat, rings[0])) continue;
    let hole = false;
    for (let h = 1; h < rings.length; h++) {
      if (pointInRing(lon, lat, rings[h])) { hole = true; break; }
    }
    if (!hole) return true;
  }
  return false;
}

const LAT_STEP = 2.6;
const dots = [];
for (let lat = -84; lat <= 84; lat += LAT_STEP) {
  const circumference = Math.cos((lat * Math.PI) / 180);
  if (circumference <= 0.02) continue;
  const lonStep = LAT_STEP / circumference;
  for (let lon = -180; lon < 180; lon += lonStep) {
    if (onLand(lon, lat)) {
      dots.push(Math.round(lat * 10) / 10, Math.round(lon * 10) / 10);
    }
  }
}

const body =
  '/* Dotted land for the background globe.\n' +
  '   Generated by scripts/gen-earth.js from Natural Earth 1:110m land\n' +
  '   (public domain). Flat array of lat, lon pairs. */\n' +
  'window.DCP_EARTH = ' + JSON.stringify(dots) + ';\n';

fs.writeFileSync(output, body);
console.log(
  'wrote ' + output + ' — ' + dots.length / 2 + ' land dots, ' +
  (Buffer.byteLength(body) / 1024).toFixed(1) + ' KB'
);
